# Generated by Django 5.1.2 on 2024-10-26 20:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch24app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('custom_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=255, verbose_name='Program Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('genre', models.CharField(blank=True, max_length=255, verbose_name='Genre (e.g.News, Comedy, Talk Show)')),
                ('age_rating', models.CharField(blank=True, max_length=255, verbose_name='Age Rating (e.g. TV-14, TV-MA)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ch24app.creator')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('custom_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('episode_number', models.IntegerField(verbose_name='Episode Number')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('repeat_preferences', models.CharField(blank=True, max_length=255, verbose_name='Repeat Preferences (e.g. daily, weekly, or specific day/time)')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ch24app.program')),
            ],
        ),
    ]
