# Generated by Django 5.1.2 on 2024-10-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch24app', '0002_program_episode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='company',
            field=models.CharField(blank=True, max_length=200, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='phone',
            field=models.CharField(blank=True, max_length=25, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='zip_code',
            field=models.CharField(blank=True, max_length=16, verbose_name='Zip Code'),
        ),
    ]
