# Generated by Django 5.1.2 on 2024-10-26 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ch24app', '0003_alter_creator_company_alter_creator_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='program_id',
            new_name='program',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='creator_id',
            new_name='creator',
        ),
    ]
