# Generated by Django 5.1.2 on 2024-10-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch24app', '0004_rename_program_id_episode_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
