# Generated by Django 5.1.2 on 2024-11-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch24app', '0006_creator_created_by_episode_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='file_name',
            field=models.TextField(blank=True, verbose_name='File Name'),
        ),
    ]
