# Generated by Django 5.1.2 on 2024-11-02 17:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch24app', '0008_alter_episode_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='custom_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
