# Generated by Django 5.1.3 on 2024-11-08 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch24app', '0009_alter_episode_custom_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.IntegerField()),
                ('metadata', models.JSONField()),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_infos', to='ch24app.episode')),
            ],
        ),
    ]
