# Generated by Django 5.1.3 on 2024-11-08 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ch24app', '0010_mediainfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MediaInfo',
            new_name='EpisodeMediaInfo',
        ),
    ]
