# Generated by Django 5.1.3 on 2024-11-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch24app', '0011_rename_mediainfo_episodemediainfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='genre',
            field=models.CharField(blank=True, choices=[('News/Weather Report', 'News/Weather Report'), ('News Magazine', 'News Magazine'), ('Documentary', 'Documentary'), ('Discussion/Interview/Debate', 'Discussion/Interview/Debate'), ('Talk Show', 'Talk Show'), ('Performing Arts', 'Performing Arts'), ('Fine Arts', 'Fine Arts'), ('Religion', 'Religion'), ('Popular Culture/Traditional Arts', 'Popular Culture/Traditional Arts'), ('Rock/Pop', 'Rock/Pop'), ('Folk/Traditional Music', 'Folk/Traditional Music'), ('Sports Magazine', 'Sports Magazine'), ('Team Sports', 'Team Sports'), ('Entertainment Programmes for 6-14', 'Entertainment Programmes for 6-14'), ('Informational/Educational/School Programmes', 'Informational/Educational/School Programmes'), ('Nature/Animals/Environment', 'Nature/Animals/Environment'), ('Technology/Natural Sciences', 'Technology/Natural Sciences'), ('Medicine/Physiology/Psychology', 'Medicine/Physiology/Psychology'), ('Magazines/Reports/Documentary', 'Magazines/Reports/Documentary'), ('Economics/Social Advisory', 'Economics/Social Advisory'), ('Tourism/Travel', 'Tourism/Travel'), ('Handicraft', 'Handicraft'), ('Fitness and Health', 'Fitness and Health'), ('Cooking', 'Cooking')], max_length=50, verbose_name='Genre'),
        ),
    ]
