# Generated by Django 5.1.3 on 2024-11-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch24app', '0012_alter_program_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='age_rating',
            field=models.CharField(blank=True, choices=[('TV-Y', 'TV-Y: All Children'), ('TV-Y7', 'TV-Y7: Directed to Older Children'), ('TV-G', 'TV-G: General Audience'), ('TV-PG', 'TV-PG: Parental Guidance Suggested'), ('TV-14', 'TV-14: Parents Strongly Cautioned'), ('TV-MA', 'TV-MA: Mature Audience Only')], max_length=10, verbose_name='Age Rating'),
        ),
    ]
