# Generated by Django 5.1.3 on 2024-11-20 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ch24app', '0014_supportticket_ticketresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='created_by',
        ),
    ]
