# Generated by Django 5.1.3 on 2024-11-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ch24app", "0016_supportticket_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="has_mediainfo_errors",
            field=models.BooleanField(default=False),
        ),
    ]
