# Generated by Django 5.1.3 on 2024-11-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ch24app", "0017_episode_has_mediainfo_errors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="has_mediainfo_errors",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
