# Generated by Django 5.1.3 on 2024-11-23 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ch24app", "0020_remove_creator_company_creator_channel_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episode",
            name="repeat_preferences",
        ),
    ]
