# Generated by Django 5.1.3 on 2024-11-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ch24app", "0021_remove_episode_repeat_preferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creator",
            name="channel_name",
            field=models.CharField(
                blank=True, max_length=200, unique=True, verbose_name="Channel Name"
            ),
        ),
    ]
