# Generated by Django 5.1.3 on 2024-11-24 18:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ch24app", "0022_alter_creator_channel_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="EpisodeProcessingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("stop_time", models.DateTimeField(blank=True, null=True)),
                (
                    "completion_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "aws_transaction_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("errors", models.TextField(blank=True)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ch24app.episode",
                    ),
                ),
            ],
        ),
    ]
