# Generated by Django 5.1.3 on 2024-12-03 19:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ch24app", "0024_episode_ai_age_rating_episode_ai_genre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="ai_topics",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
