# Generated by Django 5.1.3 on 2024-12-04 18:43

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ch24app", "0025_episode_ai_topics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episode",
            name="ai_age_rating",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="ai_genre",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="ai_summary",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="ai_topics",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="last_scheduled",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="last_timeslot",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="schedule_count",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="transcription",
        ),
        migrations.CreateModel(
            name="Transcription",
            fields=[
                (
                    "custom_id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transcription",
                    models.TextField(blank=True, verbose_name="Transcription"),
                ),
                ("ai_summary", models.TextField(blank=True, verbose_name="AI Summary")),
                (
                    "ai_genre",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="AI Generated Genre"
                    ),
                ),
                (
                    "ai_age_rating",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        verbose_name="AI Generated Age Rating",
                    ),
                ),
                (
                    "ai_topics",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_scheduled",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Scheduled Time"
                    ),
                ),
                (
                    "last_timeslot",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Last Time Slot"
                    ),
                ),
                (
                    "schedule_count",
                    models.IntegerField(default=0, verbose_name="Schedule Count"),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ch24app.episode",
                    ),
                ),
            ],
        ),
    ]
