# Generated by Django 4.2.17 on 2024-12-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch24app', '0027_analysis_episode_last_scheduled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='last_timeslot',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Time Slot'),
        ),
    ]
