# Generated by Django 5.1.3 on 2024-12-12 14:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch24app', '0029_alter_episode_schedule_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='prohibited_content',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='analysis',
            name='prohibited_content_reasons',
            field=models.TextField(blank=True, verbose_name='Prohibited Content Reasons'),
        ),
    ]
