# Generated by Django 4.2.17 on 2024-12-13 15:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch24app', '0030_analysis_prohibited_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='ai_age_rating',
            field=models.CharField(blank=True, choices=[('TV-Y', 'TV-Y: All Children'), ('TV-Y7', 'TV-Y7: Directed to Older Children'), ('TV-G', 'TV-G: General Audience'), ('TV-PG', 'TV-PG: Parental Guidance Suggested'), ('TV-14', 'TV-14: Parents Strongly Cautioned'), ('TV-MA', 'TV-MA: Mature Audience Only')], max_length=10, verbose_name='AI Generated Age Rating'),
        ),
        migrations.AddField(
            model_name='episode',
            name='ai_genre',
            field=models.CharField(blank=True, choices=[('News/Weather Report', 'News/Weather Report'), ('News Magazine', 'News Magazine'), ('Documentary', 'Documentary'), ('Discussion/Interview/Debate', 'Discussion/Interview/Debate'), ('Talk Show', 'Talk Show'), ('Performing Arts', 'Performing Arts'), ('Fine Arts', 'Fine Arts'), ('Religion', 'Religion'), ('Popular Culture/Traditional Arts', 'Popular Culture/Traditional Arts'), ('Rock/Pop', 'Rock/Pop'), ('Folk/Traditional Music', 'Folk/Traditional Music'), ('Sports Magazine', 'Sports Magazine'), ('Team Sports', 'Team Sports'), ('Entertainment Programmes for 6-14', 'Entertainment Programmes for 6-14'), ('Informational/Educational/School Programmes', 'Informational/Educational/School Programmes'), ('Nature/Animals/Environment', 'Nature/Animals/Environment'), ('Technology/Natural Sciences', 'Technology/Natural Sciences'), ('Medicine/Physiology/Psychology', 'Medicine/Physiology/Psychology'), ('Magazines/Reports/Documentary', 'Magazines/Reports/Documentary'), ('Economics/Social Advisory', 'Economics/Social Advisory'), ('Tourism/Travel', 'Tourism/Travel'), ('Handicraft', 'Handicraft'), ('Fitness and Health', 'Fitness and Health'), ('Cooking', 'Cooking')], max_length=50, verbose_name='AI Generated Genre'),
        ),
        migrations.AddField(
            model_name='episode',
            name='ai_summary',
            field=models.TextField(blank=True, verbose_name='AI Summary'),
        ),
        migrations.AddField(
            model_name='episode',
            name='ai_time_slots_recommended',
            field=models.CharField(blank=True, max_length=255, verbose_name='Time Slots Requested'),
        ),
        migrations.AddField(
            model_name='episode',
            name='ai_topics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='episode',
            name='audience_engagement_reasons',
            field=models.TextField(blank=True, verbose_name='Audience Engagement Reasons'),
        ),
        migrations.AddField(
            model_name='episode',
            name='audience_engagement_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Audience Engagement Score'),
        ),
        migrations.AddField(
            model_name='episode',
            name='prohibited_content',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='episode',
            name='prohibited_content_reasons',
            field=models.TextField(blank=True, null=True, verbose_name='Prohibited Content Reasons'),
        ),
        migrations.AddField(
            model_name='episode',
            name='ready_for_air',
            field=models.BooleanField(db_index=True, default=True, help_text='Indicates whether this content is ready for scheduling.', verbose_name='Ready for Air'),
        ),
        migrations.AddField(
            model_name='episode',
            name='transcription',
            field=models.TextField(blank=True, verbose_name='Transcription'),
        ),
        migrations.DeleteModel(
            name='Analysis',
        ),
    ]
