# Generated by Django 4.2.17 on 2024-12-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch24app', '0035_manual_field_removal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledepisode',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='scheduledepisode',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
    ]
