# Generated by Django 4.2.17 on 2024-12-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch24app', '0036_alter_scheduledepisode_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='priority_score',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Priority Score'),
        ),
    ]
