# Generated by Django 5.1.3 on 2025-02-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch24app', '0039_streamsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='override_age_rating',
            field=models.CharField(blank=True, choices=[('TV-Y', 'TV-Y: All Children'), ('TV-Y7', 'TV-Y7: Directed to Older Children'), ('TV-G', 'TV-G: General Audience'), ('TV-PG', 'TV-PG: Parental Guidance Suggested'), ('TV-14', 'TV-14: Parents Strongly Cautioned'), ('TV-MA', 'TV-MA: Mature Audience Only')], max_length=10, verbose_name='Override Age Rating'),
        ),
        migrations.AddField(
            model_name='program',
            name='override_day_of_week',
            field=models.CharField(blank=True, choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3, verbose_name='Override Day of Week'),
        ),
        migrations.AddField(
            model_name='program',
            name='override_time_slots',
            field=models.CharField(blank=True, max_length=255, verbose_name='Override Time Slots Requested'),
        ),
    ]
