# Generated by Django 5.1.3 on 2025-02-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch24app', '0040_program_override_age_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='time_slots_requested',
            field=models.CharField(blank=True, choices=[('overnight', 'Overnight (2 AM - 6 AM)'), ('early_morning', 'Early Morning (6 AM - 9 AM)'), ('daytime', 'Daytime (9 AM - 3 PM)'), ('after_school', 'After School (3 PM - 6 PM)'), ('early_evening', 'Early Evening (6 PM - 8 PM)'), ('prime_time', 'Prime Time (8 PM - 11 PM)'), ('late_night', 'Late Night (11 PM - 2 AM)')], max_length=255, verbose_name='Time Slots Requested'),
        ),
    ]
